### ISSUE TITLE
Add rules for ES2025, which was added in October 2024

### ISSUE THREAD

**Issue by ota-meshi** [eslint-community/eslint-plugin-es-x#201]
- [x] New rule for [RegExp Modifiers](https://github.com/tc39/proposal-regexp-modifiers) #208 
- [x] New rule for [Import Attributes](https://github.com/tc39/proposal-import-attributes) #209
- [x] New rule for [JSON Modules](https://github.com/tc39/proposal-json-modules) #210
- [ ] New rule for [Sync Iterator helpers](https://github.com/tc39/proposal-iterator-helpers) #211
  - [x] Iterator
  - [x] Iterator.prototype.drop()
  - [x] Iterator.prototype.every()
  - [x] Iterator.prototype.filter()
  - [x] Iterator.prototype.find()
  - [x] Iterator.prototype.flatMap()
  - [x] Iterator.prototype.forEach()
  - [x] Iterator.prototype.map()
  - [x] Iterator.prototype.reduce()
  - [x] Iterator.prototype.some()
  - [x] Iterator.prototype.take()
  - [x] Iterator.prototype.toArray()
- [x] New rule for [Promise.try](https://github.com/tc39/proposal-promise-try) #212
